import { describe, expect, it } from 'vitest';

import { generateShellInit } from '../src/core/shell-init.ts';

describe('generateShellInit', () => {
    it('emits a bash/zsh function per profile, delegating via `command`', () => {
        const { script, skipped } = generateShellInit('bash', 'cpane', [
            'app',
            'web',
        ]);
        expect(skipped).toEqual([]);
        expect(script).toContain('app() { command cpane app "$@"; }');
        expect(script).toContain('web() { command cpane web "$@"; }');
    });

    it('zsh output is the same shape as bash', () => {
        const { script } = generateShellInit('zsh', 'cpane', ['app']);
        expect(script).toContain('app() { command cpane app "$@"; }');
    });

    it('emits a pwsh function per profile', () => {
        const { script } = generateShellInit('pwsh', 'cpane', ['app', 'web']);
        expect(script).toContain('function app { cpane app @args }');
        expect(script).toContain('function web { cpane web @args }');
    });

    it('skips profile names that are not safe shell identifiers', () => {
        const { script, skipped } = generateShellInit('bash', 'cpane', [
            'app',
            'has space',
            '2fa',
        ]);
        expect(skipped).toEqual(['has space', '2fa']);
        expect(script).toContain('app()');
        expect(script).not.toContain('has space');
        expect(script).not.toContain('2fa');
    });

    it('skips a profile named after the binary itself, to avoid self-recursion', () => {
        const { script, skipped } = generateShellInit('bash', 'cpane', [
            'cpane',
            'app',
        ]);
        expect(skipped).toEqual(['cpane']);
        expect(script).not.toContain('cpane() {');
        expect(script).toContain('app() { command cpane app "$@"; }');
    });

    it('includes a header comment and no profile lines for an empty list', () => {
        const { script, skipped } = generateShellInit('bash', 'cpane', []);
        expect(skipped).toEqual([]);
        expect(script).toContain('Generated by `cpane shell-init bash`');
    });
});
