export type ShellKind = 'bash' | 'zsh' | 'pwsh';

export const SHELL_KINDS: ShellKind[] = ['bash', 'zsh', 'pwsh'];

const SAFE_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_-]*$/;

export interface ShellInitResult {
    script: string;
    /** Profile names that can't safely become a shell function/alias. */
    skipped: string[];
}

/**
 * One shell function per profile, delegating to `<binaryName> <profile>` —
 * the shell-native equivalent of the per-host PowerShell functions cPane
 * replaces (PRD §10). Meant to be eval'd from the shell's startup file so it
 * stays in sync as profiles are added/removed, e.g.
 * `eval "$(cpane shell-init bash)"` in `.bashrc`.
 *
 * `command`/an explicit call operator guards against the (unlikely) case of
 * a profile literally named after the binary recursing into itself; a
 * profile whose name isn't a safe shell identifier, or that collides with
 * `binaryName`, is skipped rather than emitting broken/dangerous script.
 */
export function generateShellInit(
    shell: ShellKind,
    binaryName: string,
    profileNames: string[],
): ShellInitResult {
    const usable = profileNames.filter(
        name => SAFE_IDENTIFIER.test(name) && name !== binaryName,
    );
    const skipped = profileNames.filter(name => !usable.includes(name));

    const header = [
        `# Generated by \`${binaryName} shell-init ${shell}\` — one function per profile.`,
        `# Re-eval (e.g. open a new shell) after adding/removing profiles to pick up changes.`,
    ];

    const body =
        shell === 'pwsh'
            ? usable.map(
                  name => `function ${name} { ${binaryName} ${name} @args }`,
              )
            : usable.map(
                  name => `${name}() { command ${binaryName} ${name} "$@"; }`,
              );

    return { script: [...header, ...body].join('\n'), skipped };
}
